#Версия docker-compose
version: '3'
services:
  zookeeper1:
    container_name: zookeeper1
    image: zk:1   
    ports:
      - 2181:2181
 #Объединяем в одну сеть
    networks:
      - lan
    volumes:
      - zookeeper:/opt/kafka/data
      # - ./zookeeper1/myid:/opt/zookeeper/data/myid
      - ./zookeeper1/zookeeper.properties:/opt/kafka/config/server.properties
  kafka1:
    image: kfk:1
    container_name: kafka1
    ports:
      - 9092:9092
      - 9010:9010
    networks:
      - lan
 #Зависимость от всех машин zookeeper(они должны стартовать первыми)
    depends_on:
      - zookeeper1
    # environment:
    #   - KAFKA_OPTS="-Djava.security.auth.login.config=/opt/kafka/config/kafka_server.jaas"
    volumes:
      - ./kafka1/server.properties:/opt/kafka/config/server.properties
      # - ./kafka1/kafka_server.jaas:/opt/kafka/config/kafka_server.jaas
      - kafka_data_1:/opt/kafka/data
  kafka2:
    image: kfk:1
    container_name: kafka2
    ports:
      - 9093:9093
      - 9011:9011
    networks:
      - lan
    depends_on:
      - zookeeper1
    # environment:
    #   - KAFKA_OPTS="-Djava.security.auth.login.config=/opt/kafka/config/kafka_server.jaas"
    volumes:
      - ./kafka2/server.properties:/opt/kafka/config/server.properties
      # - ./kafka2/kafka_server.jaas:/opt/kafka/config/kafka_server.jaas
      - kafka_data_2:/opt/kafka/data
  kafka3:
    image: kfk:1
    container_name: kafka3
    ports:
      - 9094:9094
      - 9012:9012
    networks:
      - lan
    depends_on:
      - zookeeper1
    # environment:
    #   - KAFKA_OPTS="-Djava.security.auth.login.config=/opt/kafka/config/kafka_server.jaas"
    volumes:
      # - ./kafka3/kafka_server.jaas:/opt/kafka/config/kafka_server.jaas
      - ./kafka3/server.properties:/opt/kafka/config/server.properties
      - kafka_data_3:/opt/kafka/data
#Объявляем сеть, к которой подключены наши сервисы
networks:
  lan:
volumes:
  kafka_data_1: {}
  kafka_data_2: {}
  kafka_data_3: {}
  zookeeper: {}
