#Задаем базовый образ(ОС)
FROM ubuntu
#Устанавливаем Ява машину curl и tar чтобы скачать kafka
RUN apt update && apt install -y default-jre curl tar
#Создаем каталог, в котором kafka будет работать
RUN mkdir /opt/kafka
#Скачаиваем
RUN curl "https://downloads.apache.org/kafka/3.3.2/kafka_2.12-3.3.2.tgz" -o /opt/kafka/kafka.tgz
#Распаковываем
RUN tar -xvzf /opt/kafka/kafka.tgz && rm -rf /opt/kafka/kafka.tgz
#Перемещаем в наш каталог
RUN mv /kafka*/* /opt/kafka
#Запускаем
ENTRYPOINT /opt/kafka/bin/zookeeper-server-start.sh /opt/kafka/config/zookeeper.properties
