FROM ubuntu
RUN apt update && apt install -y default-jre curl tar 
RUN mkdir /opt/kafka
RUN curl "https://downloads.apache.org/kafka/3.3.2/kafka_2.12-3.3.2.tgz" -o /opt/kafka/kafka.tgz
RUN tar -xvzf /opt/kafka/kafka.tgz && rm -rf /opt/kafka/kafka.tgz
RUN mv /kafka*/* /opt/kafka
ENTRYPOINT /opt/kafka/bin/zookeeper-server-start.sh /opt/kafka/config/zookeeper.properties
